### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Thanks for your amazing work!
Here is a proposal of translation in French.
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by ghost** [comment]
Hello, could you please take some time to consider my pull request?
I thank you in advance.

**Comment by michelRenon** [comment]
Hi Anne017,
Thanks for your interest about this project !
Sorry for the delay, I'm working on it on my free time.

Since last public commit (27 mars), I worked on upgrading code to last SDK version. It requires some changes in list views, headers, pages... I also started to integrate some of your pull request, but as the UI and code change, the list of translation strings also change.
The current work is not yet public because some parts are still under investigation (ex: handling of AdaptativePageLayout).
As soon as a UI/string freeze is reached, I'll keep you informed and I'll start using launchpad for translations.
Thanks again for your interest and patience.
Michel

**Comment by ghost** [comment]
Hello! Do you have some time to review this pull request?

**Comment by michelRenon** [comment]
Hi Anne,
I finally found time to search and push all work in progress, waiting since 2016...
There is an update on branch 'ucomponents_1.3' and then some tests on displaying flags list.
You can use and continue developments, as I stopped working on it.
I hope it will be useful.
Cheers

**Pull request closed without merging**
